import type { FxTable } from './fx'
import { convertCurrency } from './fx'
import type { Currency,MarketQuote,Position,Transaction,ValuedPosition } from './models'
const round=(v:number)=>Math.round((v+Number.EPSILON)*1e6)/1e6
export function reconstructPositions(transactions:Transaction[]):Position[]{const map=new Map<string,Position>();for(const tx of [...transactions].sort((a,b)=>a.date.getTime()-b.date.getTime())){if(!tx.assetId)continue;const p=map.get(tx.assetId)??{assetId:tx.assetId,quantity:0,averageCost:0,costBasis:0,realizedPnl:0,income:0,fees:0};if(tx.type==='BUY'){const q=tx.quantity??0,cost=q*(tx.unitPrice??0)+tx.fees;p.costBasis+=cost;p.quantity+=q;p.averageCost=p.quantity? p.costBasis/p.quantity:0;p.fees+=tx.fees}else if(tx.type==='SELL'){const q=tx.quantity??0;if(q>p.quantity)throw new Error(`Cannot sell more ${tx.assetId} than currently held`);const removed=p.averageCost*q;p.realizedPnl+=q*(tx.unitPrice??0)-tx.fees-removed;p.costBasis-=removed;p.quantity-=q;p.fees+=tx.fees;if(!p.quantity){p.averageCost=0;p.costBasis=0}}else if(tx.type==='DIVIDEND')p.income+=tx.amount??0;else if(tx.type==='FEE')p.fees+=Math.abs(tx.amount??tx.fees);map.set(tx.assetId,p)}return [...map.values()].map(p=>({...p,quantity:round(p.quantity),averageCost:round(p.averageCost),costBasis:round(p.costBasis),realizedPnl:round(p.realizedPnl),income:round(p.income),fees:round(p.fees)}))}
export function valuePositions(positions:Position[],quotes:MarketQuote[],base:Currency,rates:FxTable):ValuedPosition[]{const qmap=new Map(quotes.map(q=>[q.assetId,q]));const partial=positions.map(p=>{const q=qmap.get(p.assetId),marketValue=q?.price==null?null:q.price*p.quantity,valueInBaseCurrency=marketValue==null||!q?null:convertCurrency(marketValue,q.currency,base,rates),costBasisInBaseCurrency=!q?null:convertCurrency(p.costBasis,q.currency,base,rates);return{...p,marketPrice:q?.price??null,marketValue,valueInBaseCurrency,unrealizedPnl:valueInBaseCurrency==null||costBasisInBaseCurrency==null?null:valueInBaseCurrency-costBasisInBaseCurrency,weight:null}});const total=partial.reduce((s,p)=>s+(p.valueInBaseCurrency??0),0);return partial.map(p=>({...p,weight:p.valueInBaseCurrency==null||!total?null:p.valueInBaseCurrency/total}))}
export function portfolioValue(p:ValuedPosition[]):number|null{return p.some(x=>x.valueInBaseCurrency===null)?null:p.reduce((s,x)=>s+(x.valueInBaseCurrency??0),0)}
export function investedCapital(t:Transaction[]):number{return t.reduce((s,x)=>x.type==='DEPOSIT'?s+Math.abs(x.amount??0):x.type==='WITHDRAWAL'?s-Math.abs(x.amount??0):s,0)}
export function concentrationScore(p:ValuedPosition[]):number|null{return p.some(x=>x.weight===null)?null:p.reduce((s,x)=>s+(x.weight??0)**2,0)}
export function maxDrawdown(values:number[]):number|null{if(!values.length)return null;let peak=values[0],worst=0;for(const v of values){peak=Math.max(peak,v);if(peak>0)worst=Math.min(worst,(v-peak)/peak)}return worst}
